### ISSUE TITLE
Switch back to macfsevents - it performs better

### ISSUE THREAD

**Issue by EugenMayer** [jumpstarter-io/unox#17]
@hnsl i know that you actually do not want to dedicate a lot / any time to this project, but i guess i need some kind of transfer-time.

What reasons did you had to pick up watchdog? it seem to underperform quiet a bit https://github.com/EugenMayer/docker-sync/issues/308 - can you elaborate a bit?

Thanks!

**Comment by hnsl** [comment]
No problem, see: https://github.com/hnsl/unox/pull/8

**Comment by EugenMayer** [comment]
Closing this for now, since there is some evidence, that watchdog does perform better in terms of reliability. Lets see what happens long term
