### ISSUE TITLE
Error while install with brew

### ISSUE THREAD

**Issue by arioch1984** [jumpstarter-io/unox#23]
Hi...

...Thank's for your work!

I followed your instructions for installing via homebrew, but when I call brew install I have this error:
`MacBook-Pro-di-Fabio-2:~ fabiobrunelli$ brew install eugenmayer/dockersync/unox
==> Installing unox from eugenmayer/dockersync
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/fabiobrunelli/Library/Caches/Homebrew/unox-0.2.0.0
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
Already downloaded: /Users/fabiobrunelli/Library/Caches/Homebrew/unox--homebrew-virtualenv-15.1.0.tar.gz
==> python2.7 -c import setuptools... --no-user-cfg install --prefix=/tmp/unox--homebrew-virtualenv-20180307-12325-142vvkl/target --single-version-externally-managed --record=installed.txt
==> python2.7 -s /tmp/unox--homebrew-virtualenv-20180307-12325-142vvkl/target/bin/virtualenv -p python2.7 /usr/local/Cellar/unox/0.2.0_1/libexec
==> Downloading https://pypi.python.org/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz
Already downloaded: /Users/fabiobrunelli/Library/Caches/Homebrew/unox--watchdog-0.8.3.tar.gz
==> /usr/local/Cellar/unox/0.2.0_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/unox--watchdog-20180307-12325-1je6u0i/watchdog-0.8.3
Last 15 lines from /Users/fabiobrunelli/Library/Logs/Homebrew/unox/03.pip:
  Removing source in /private/tmp/pip-PjERgM-build
Command "/usr/local/Cellar/unox/0.2.0_1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-PjERgM-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6nCpUX-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/unox/0.2.0_1/libexec/include/site/python2.7/watchdog" failed with error code 1 in /private/tmp/pip-PjERgM-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/unox/0.2.0_1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-PjERgM-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6nCpUX-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/unox/0.2.0_1/libexec/include/site/python2.7/watchdog" failed with error code 1 in /private/tmp/pip-PjERgM-build/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/eugenmayer/homebrew-dockersync/issues`

Please may you help me?

**Comment by hnsl** [comment]
As mentioned in the last line, you should probably report this here:

https://github.com/EugenMayer/homebrew-dockersync/issues

Note that this does not appear to be a unox issue.
